doc: Test nested prefixes with arrays
output:
  args:
  - bwa
  - mem
  - chr20.fa
  - -XXX
  - -YYY
  - example_human_Illumina.pe_1.fastq
  - -YYY
  - example_human_Illumina.pe_2.fastq
tags:
- required
