doc: Test simple workflow with a dynamic resource requirement
output:
  cores:
    checksum: sha1$7448d8798a4380162d4b56f9b452e2f6f9e24e7a
    class: File
    location: output
    size: 2
tags:
- resource
