doc: Test command line with stderr redirection, named brief syntax
output:
  output_file:
    checksum: sha1$f1d2d2f924e986ac86fdf7b36c94bcdf32beec15
    class: File
    location: std.err
    size: 4
tags:
- shell_command
