doc: Test workflow scatter with two scatter parameters and flat_crossproduct join
  method and valueFrom on step input
output:
  out:
  - foo one one three
  - foo one one four
  - foo one two three
  - foo one two four
tags:
- scatter
- step_input
