doc: Test record type output binding.
output:
  orec:
    obar:
      checksum: sha1$aeb3d11bdf536511649129f4077d5cda6a324118
      class: File
      location: bar
      size: 12010
    ofoo:
      checksum: sha1$327fc7aedf4f6b69a42a7c8b808dc5a7aff61376
      class: File
      location: foo
      size: 1111
tags:
- shell_command
