doc: Test directory output
output:
  outdir:
    class: Directory
    listing:
    - checksum: sha1$dd0a4c4c49ba43004d6611771972b6cf969c1c01
      class: File
      location: goodbye.txt
      size: 24
    - checksum: sha1$47a013e660d408619d894b20806b1d5086aab03b
      class: File
      location: hello.txt
      size: 13
tags:
- required
