doc: Test InlineJavascriptRequirement with multiple expressions in the same tool
output:
  args:
  - -A
  - "2"
  - -B
  - baz
  - -C
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "3"
  - "2"
  - "1"
tags:
- inline_javascript
