doc: Test directory literal output created by ExpressionTool
output:
  dir:
    class: Directory
    listing:
    - checksum: sha1$327fc7aedf4f6b69a42a7c8b808dc5a7aff61376
      class: File
      location: whale.txt
      size: 1111
    - checksum: sha1$47a013e660d408619d894b20806b1d5086aab03b
      class: File
      location: hello.txt
      size: 13
    location: a_directory
tags:
- inline_javascript
