doc: |
  Test optional output file and optional secondaryFile on output.
output:
  optional_file: null
  output_file:
    checksum: sha1$47a013e660d408619d894b20806b1d5086aab03b
    class: File
    location: output.txt
    size: 13
tags:
- docker
