doc: Test nameroot/nameext expression in arguments, stdout
output:
  b:
    checksum: sha1$c4cfd130e7578714e3eef91c1d6d90e0e0b9db3e
    class: File
    location: whale.xtx
    size: 21
tags:
- required
