doc: Test dynamic initial work dir
output:
  outlist:
    checksum: sha1$13cda8661796ae241da3a18668fb552161a72592
    class: File
    location: output.txt
    size: 20
tags:
- shell_command
- initial_work_dir
