doc: Test that ResourceRequirement on a step level redefines requirement on the workflow
  level
output:
  out:
    checksum: sha1$e5fa44f2b31c1fb553b6021e7360d07d5d91ff5e
    class: File
    location: cores.txt
    size: 2
tags:
- resource
